import tkinter as tk
import pyautogui
from time import sleep
import os
import sys
import shutil
from tkinter import ttk
from tkinter import messagebox
import subprocess
from time import *
import subprocess
import requests
import pyttsx3

engine = pyttsx3.init()

engine.setProperty('rate', 150)

engine.setProperty('volume', 1)
pa = os.getcwd()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)
text=f"hello {pa}, how are you? , nice to see you again!"
engine.say(text)
engine.runAndWait()



try:
    url = "https://github.com/hazem589799/Hazem589799/archive/refs/heads/main.zip"
    local_zip_path = "Hazem589799.zip"
    new_program_path = "Hazem589799/HA.py"
                
    response = requests.get(url)
    with open(local_zip_path, 'wb') as file:
        file.write(response.content)
                
    with zipfile.ZipFile(local_zip_path, 'r') as zip_ref:
                    zip_ref.extractall()
                
    subprocess.call([
                    'pyinstaller', '--onefile', '--distpath', '.', '--workpath', '.', '--specpath', '.', new_program_path
                ])
                
    exe_file = "HA.exe"
    original_path = os.path.abspath(__file__)
    original_dir = os.path.dirname(original_path)
    new_exe_path = os.path.join(original_dir, exe_file)
                
    if os.path.isfile(new_exe_path):
        os.remove(new_exe_path)
            
    shutil.move(os.path.join('.', exe_file), new_exe_path)
    os.remove(local_zip_path)
    shutil.rmtree('Hazem589799-main')
    subprocess.call([new_exe_path])
    wd.destroy()
    
except Exception as e:
    messagebox.showerror("خطأ", f"لسه مفيش تحديثات اترفعت على الانترنت  لا تقلق سيتم رفعها فى اسرع وقت: {e}")


def show():
    #print(pyautogui.countdown(2))
    sleep(2)
    sho = pyautogui.position()
    lbl2 = tk.Label(text=sho , fg="blue" , font=("Arial" , 10 ))
    lbl2.pack(pady=6)
def strto():
    pyautogui.click(1220 , 737)
    sleep(1)
    pyautogui.press('enter')
    sleep(0.5)
    pyautogui.press('enter')
    sleep(0.5)
    pyautogui.press('tab')
    pyautogui.press('enter')
    pyautogui.press('win')
    sleep(0.5)
    pyautogui.press('win')
    sleep(0.5)
    pyautogui.hotkey('win' , '2')
    sleep(0.5)
    pyautogui.click(986 , 58)
    sleep(0.5)
    pyautogui.click(793 , 75)
    sleep(3)
    pyautogui.click(1024 , 430)
    sleep(0.5)
    pyautogui.write("doaa.abdelhay")
    pyautogui.press('enter')
    pyautogui.write("d.abdelhay")
    pyautogui.press('enter')
def close_o():
    pyautogui.click(1220 , 737)
    sleep(1)
    pyautogui.press('enter')
    sleep(0.5)
    pyautogui.press('enter')
    sleep(0.5)
    pyautogui.press('tab')
    pyautogui.press('enter')
    pyautogui.press('win')
    sleep(0.5)
    pyautogui.press('win')
def sign():
    pyautogui.click(1020 ,431)
    pyautogui.write("doaa.abdelhay")
    pyautogui.press('enter')
    pyautogui.write("d.abdelhay")
    pyautogui.press('enter')

def esnadaa():
    x = int(txt_time.get())
    x -= 1
    for b in range(x):
        pyautogui.keyDown('win')
        for m in range(2):
            pyautogui.press('3')
            sleep(0.8)
        pyautogui.keyUp('win')
        sleep(0.6)
        pyautogui.press('down')   
        pyautogui.keyDown('ctrl')
        pyautogui.press('c')
        pyautogui.keyUp('ctrl')
        sleep(0.6)
        pyautogui.keyDown('win')
        pyautogui.press('2')
        sleep(0.6)
        pyautogui.press('2')
        pyautogui.keyUp('win')
        sleep(1.6)
        pyautogui.press('down')
        sleep(0.6)
        pyautogui.press('enter')
        sleep(0.6)
        pyautogui.keyDown('ctrl')
        pyautogui.press('v')
        pyautogui.keyUp('ctrl')
        sleep(0.6)
        pyautogui.press('enter')
        sleep(0.6)
        pyautogui.press('enter')
        sleep(0.6)
        pyautogui.press('down')
def un():
    sleep(0.5)
    pyautogui.click(1101 , 541)
    sleep(2)
    pyautogui.write('hguk,hk ydv ,hqp ,hgihjt ydv ljhp h;ev lk lvm')
    sleep(1)
    pyautogui.doubleClick(854 , 475)
    sleep(1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('enter')
    sleep(1)
    pyautogui.press('tab')
    sleep(0.5)
    pyautogui.press('tab')
    sleep(0.1)
    pyautogui.hotkey('alt' , 'down')
    sleep(0.2)
    pyautogui.press('down')
    sleep(0.2)
    pyautogui.press('enter')
    sleep(0.2)
    pyautogui.hotkey('ctrl' , 's')
    sleep(0.2)
    pyautogui.press('enter')
    sleep(0.2)
    pyautogui.press('enter')
    sleep(0.2)
    pyautogui.click(1217 , 142)
    sleep(3)
    pyautogui.click(1231 ,140)
    sleep(0.6)
    pyautogui.press('f11')
    sleep(0.2)

def warasha():
    sleep(0.5)
    pyautogui.click(1101 , 541)
    sleep(2)
    pyautogui.write('jl hghuj`hv gpdk hghkjihx lk hghwghp gd,l 15-11-2024')
    sleep(1)
    pyautogui.doubleClick(854 , 475)
    sleep(1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('down')
    sleep(0.1)
    pyautogui.press('enter')
    sleep(1)
    pyautogui.press('tab')
    sleep(0.5)
    pyautogui.press('tab')
    sleep(0.1)
    pyautogui.hotkey('alt' , 'down')
    sleep(0.2)
    pyautogui.press('down')
    sleep(0.2)
    pyautogui.press('enter')
    sleep(0.2)
    pyautogui.hotkey('ctrl' , 's')
    sleep(0.2)
    pyautogui.press('enter')
    sleep(0.2)
    pyautogui.press('enter')
    sleep(0.2)
    pyautogui.click(1223 , 140)
    sleep(3)
    pyautogui.click(1231 ,140)
    sleep(0.6)
    pyautogui.press('f11')
    sleep(0.2)
def moaina():
    pyautogui.press('enter')
    
def repor():
    m = 0.5
    while True:
        #يوجد مشكلة فى هذه الدالة حيث انه يتم وضع بعض القيم فى اماكن غير اماكنها لابد ان يتم فحص هذه المشكلة انا اعتقد ان المشكلة قد تكون ان البرنامج سريع للغاية وقد يكون الحل هو تبطئ البرنامج
        #نسخ امر الشغل
        sleep(0.1)
        pyautogui.keyDown('ctrl')
        pyautogui.press('c')
        pyautogui.keyUp('ctrl')
        pyautogui.hotkey('win' ,'3' )
        sleep(0.1)
        pyautogui.keyDown('ctrl')
        pyautogui.press('v')
        pyautogui.keyUp('ctrl')
        pyautogui.press('left')
        pyautogui.keyDown('win')
        pyautogui.press('2')
        pyautogui.press('2')
        pyautogui.keyUp('win') 


        #حالة المهمة
        pyautogui.mouseDown(271 , 361)
        pyautogui.move(395 , 361)
        pyautogui.mouseUp(395 , 361)
        sleep(0.1)
        pyautogui.keyDown('ctrl')
        sleep(int(m))
        pyautogui.press('c')
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        pyautogui.hotkey('win' , '3')
        sleep(0.1)
        #pyautogui.hotkey('ctrl' , 'v')
        pyautogui.keyDown('ctrl')
        pyautogui.press('v')
        pyautogui.keyUp('ctrl')
        pyautogui.press('left')
        pyautogui.keyDown('win')
        pyautogui.press('2')
        pyautogui.press('2')
        pyautogui.keyUp('win')

        #اسم الفنى 
        pyautogui.press('tab')
        sleep(0.1)
        pyautogui.keyDown('ctrl')
        sleep(int(m))
        pyautogui.press('c')
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        pyautogui.hotkey('win' , '3')
        sleep(0.1)
        #pyautogui.hotkey('ctrl' , 'v')
        pyautogui.keyDown('ctrl')
        pyautogui.press('v')
        pyautogui.keyUp('ctrl')
        pyautogui.press('left')
        pyautogui.keyDown('win')
        pyautogui.press('2')
        pyautogui.press('2')
        pyautogui.keyUp('win')

        #نوع المهمة
        pyautogui.mouseDown(103 , 561)
        pyautogui.move(432 , 561)
        pyautogui.mouseUp(432 , 432)
        sleep(0.1)
        pyautogui.keyDown('ctrl')
        pyautogui.press('c')
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        pyautogui.hotkey('win' , '3')
        sleep(0.1)
        #pyautogui.hotkey('ctrl' , 'v')
        pyautogui.keyDown('ctrl')
        pyautogui.press('v')
        pyautogui.keyUp('ctrl')
        pyautogui.press('left')
        pyautogui.keyDown('win')
        pyautogui.press('2')
        pyautogui.press('2')
        pyautogui.keyUp('win') 
        
        #تقرير المهمة 
        pyautogui.mouseDown(432 , 584)
        pyautogui.move(105 , 613)
        pyautogui.mouseUp(105 , 613)
        sleep(0.1)
        pyautogui.keyDown('ctrl')
        pyautogui.press('c')
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        pyautogui.hotkey('win' , '3')
        sleep(0.1)
        pyautogui.keyDown('ctrl')
        pyautogui.press('v')
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'v')
       
        pyautogui.keyDown('win')
        pyautogui.press('2')
        pyautogui.press('2')
        pyautogui.keyUp('win')
        
        

        #هنا سيتم عمل الجزء المسئول عن فتح البلاغ ونسخ حالة المهمة قد احتاج الى استدعاء مكتبة تعمل بالذكاء الاصطناعى

        #الدخول الى البلاغ
        pyautogui.doubleClick(1317 , 362)
        sleep(3)
        #تحديد نوع المهمة 
        pyautogui.mouseDown(1111 , 244)
        pyautogui.move(1291 , 243)
        pyautogui.mouseUp(1291 , 243)
    

        pyautogui.keyDown('ctrl')
        pyautogui.press('c')
        pyautogui.keyUp('ctrl')

        pyautogui.keyDown('win')
        pyautogui.press('3')
        pyautogui.keyUp('win')

        pyautogui.press('left')
        pyautogui.keyDown('ctrl')
        pyautogui.press('v')
        pyautogui.keyUp('ctrl')


        #نسخ قطع الغيار من الاوراكل الى الاكسل 
        #الدخول الى الاوراكل
        pyautogui.keyDown('win')
        pyautogui.press('2')
        pyautogui.press('2')
        pyautogui.keyUp('win')
        sleep(1)
        #الانتقال الى اخر مهمة داخل البلاغ 
        pyautogui.click(317 , 526)
        sleep(0.5)
        pyautogui.keyDown('down')
        sleep(3)
        pyautogui.keyUp('down')
        for n in range(10):
            pyautogui.press('down')
        sleep(0.5)
        pyautogui.press('enter')
        sleep(0.5)
        pyautogui.press('enter')
        sleep(1)
        #الدخول الى الجدول لنسخ قطع الغيار 
        pyautogui.click(535 , 370)
        sleep(1)
        #نسخ قطع الغيار ولصقها داخل شيت الاكسل 
        for n in range(6):
            pyautogui.keyDown('ctrl')
            pyautogui.press('c')
            pyautogui.keyUp('ctrl')

            pyautogui.keyDown('win')
            pyautogui.press('3')
            pyautogui.keyUp('win')

            pyautogui.press('left')
            pyautogui.keyDown('ctrl')
            pyautogui.press('v')
            pyautogui.keyUp('ctrl')

            pyautogui.keyDown('win')
            pyautogui.press('2')
            pyautogui.press('2')
            pyautogui.keyUp('win')

            #نقل نوع المهممة الاساسية 

            #الانتقال الى قطعة الغيار الجديدة
            pyautogui.press('down')
            
        pyautogui.press('enter')
        sleep(1)
        pyautogui.press('enter')
        #الخروج من الجدول الخاص بقطع الغيار والبلاغ بالكامل 
        pyautogui.press('f4')
        sleep(1)
        
        pyautogui.keyDown('win')
        pyautogui.press('3')
        pyautogui.keyUp('win')
        #الانتقال الى سطر جديد الخاص بالاكسل
        pyautogui.press('down')
        pyautogui.press('home')

        
        


        #الدخول الى الاوراكل مرة اخرى 
        pyautogui.keyDown('win')
        pyautogui.press('2')
        pyautogui.press('2')
        pyautogui.keyUp('win')

        #الانتقال الى سطر جديد الخاص بالاوراكل
        pyautogui.press('f6')

def oprepor():
     b = 0

     for z in range(250):
        #يوجد مشكلة فى هذه الدالة حيث انه يتم وضع بعض القيم فى اماكن غير اماكنها لابد ان يتم فحص هذه المشكلة انا اعتقد ان المشكلة قد تكون ان البرنامج سريع للغاية وقد يكون الحل هو تبطئ البرنامج
        #نسخ امر الشغل
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('c')
        sleep(b)
        pyautogui.keyUp('ctrl')
        sleep(b)
        pyautogui.keyDown('win')
        sleep(b)
        pyautogui.press('3')
        sleep(b)
        pyautogui.keyUp('win')
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('v')
        sleep(b)
        pyautogui.keyUp('ctrl')
        sleep(b)
        pyautogui.press('left')
        sleep(b)
        pyautogui.keyDown('win')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.keyUp('win') 

        sleep(b)
        """
        #حالة المهمة
        pyautogui.mouseDown(271 , 361)
        sleep(b)
        pyautogui.move(395 , 361)
        sleep(b)
        pyautogui.mouseUp(395 , 361)
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('c')
        sleep(b)
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        sleep(b)
        pyautogui.hotkey('win' , '3')
        sleep(b)
        #pyautogui.hotkey('ctrl' , 'v')
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('v')
        sleep(b)
        pyautogui.keyUp('ctrl')
        sleep(b)
        pyautogui.press('left')
        sleep(b)
        pyautogui.keyDown('win')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.keyUp('win')
        sleep(b)
        #اسم الفنى 
        pyautogui.press('tab')
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('c')
        sleep(b)
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        sleep(b)
        pyautogui.hotkey('win' , '3')
        sleep(b)
        #pyautogui.hotkey('ctrl' , 'v')
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('v')
        sleep(b)
        pyautogui.keyUp('ctrl')
        sleep(b)
        pyautogui.press('left')
        sleep(b)
        pyautogui.keyDown('win')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.keyUp('win')

        #نوع المهمة
        sleep(b)
        pyautogui.mouseDown(103 , 561)
        sleep(b)
        pyautogui.move(432 , 561)
        sleep(b)
        pyautogui.mouseUp(432 , 432)
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('c')
        sleep(b)
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        pyautogui.hotkey('win' , '3')
        sleep(b)
        #pyautogui.hotkey('ctrl' , 'v')
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('v')
        sleep(b)
        pyautogui.keyUp('ctrl')
        sleep(b)
        pyautogui.press('left')
        sleep(b)
        pyautogui.keyDown('win')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        pyautogui.keyUp('win') 
        """
        #تقرير المهمة 
        pyautogui.mouseDown(432 , 584)
        sleep(b)
        pyautogui.move(105 , 613)
        sleep(b)
        pyautogui.mouseUp(105 , 613)
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('c')
        sleep(b)
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'c')
        sleep(b)
        pyautogui.hotkey('win' , '3')
        sleep(b)
        pyautogui.keyDown('ctrl')
        sleep(b)
        pyautogui.press('v')
        sleep(b)
        pyautogui.keyUp('ctrl')
        #pyautogui.hotkey('ctrl' , 'v')
        #الانتقال الى سطر جديد الخاص بالاكسل
        sleep(b)
        pyautogui.press('down')
        sleep(b)
        pyautogui.press('home')
        sleep(b)
        pyautogui.keyDown('win')
        sleep(b)
        pyautogui.press('2')
        sleep(b)
        
        pyautogui.press('2')
        sleep(b)
        pyautogui.keyUp('win')
    
        #الانتقال الى سطر جديد الخاص بالاوراكل
        pyautogui.press('tab')
        sleep(b)
        pyautogui.press('down')    
        sleep(b)    

        
def close_app():
    wd.destroy()

def switch():
    def dam1():
        a = Txtbx.get()
        b = Txtbx2.get() # type: ignore
        c = Txtbx3.get()
        d = Txtbx4.get()
        if c == d :
            sleep(1)
            pyautogui.countdown(1)
            pyautogui.click(972 , 141)
            sleep(0.1)
            pyautogui.press('tab')
            sleep(0.1)
            pyautogui.press('tab')
            sleep(0.15)
            pyautogui.hotkey('alt' , 'down')
            sleep(0.15)
            pyautogui.press('up')
            sleep(0.15)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            pyautogui.press('tab')
            sleep(0.1)
            pyautogui.press('tab')
            sleep(0.1)
            pyautogui.write(a)
            pyautogui.write(b)
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            pyautogui.write(c)
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            pyautogui.write(d)
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            pyautogui.click(849 , 314)
            sleep(0.1)
            pyautogui.click(1037 , 334)
            sleep(0.1)
            pyautogui.write(a)
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            pyautogui.doubleClick(654 , 542)
            sleep(0.1)
            pyautogui.click(1101 , 541)
            sleep(0.1)
            pyautogui.write(str("jl hgjv;df ,hgjaydg ,hgavp ,hujlh] hgqlhk fjhvdo hghkjh["))
            sleep(0.1)
            pyautogui.doubleClick(854 , 475)
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            pyautogui.doubleClick(1090 , 240)
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            pyautogui.press('enter')
            sleep(0.1)
            def yes():
                sleep(0.1)
                pyautogui.hotkey('ctrl','s')
                sleep(0.1)
                pyautogui.press('enter')
                pyautogui.click(299 , 644)
                sleep(1)
                pyautogui.click(1068 , 373)
                sleep(0.1)
                for u in range(3):
                    pyautogui.press('down')
                    sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.press('down')
                sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.click(153 , 508)
                for b in range(3):
                    pyautogui.press('enter')
                    sleep(0.5)
                sleep(1)
                pyautogui.click(308 , 526)
                sleep(0.1)
                pyautogui.keyDown('down')
                sleep(2)
                pyautogui.keyUp('down')
                sleep(0.1)
                """
                for m in range(2):
                    pyautogui.press('enter')
                    sleep(1)
                """
                pyautogui.click(567 , 473)
                sleep(0.1)
                pyautogui.press('down')
                sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.click(851,136)
                sleep(0.1)
                pyautogui.press('down')
                sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.hotkey('ctrl','s')
                sleep(0.1)
                pyautogui.press('enter')
                Txtbx.delete(0 , tk.END)
                Txtbx2.delete(0 , tk.END)
                Txtbx3.delete(0 , tk.END)
                Txtbx4.delete(0 , tk.END)
                pyautogui.alert('تم ادخال بلاغ التركيب بنجاح')
                confirm.withdraw()

            def no(): 
                Txtbx.delete(0 , tk.END)
                Txtbx2.delete(0 , tk.END)
                Txtbx3.delete(0 , tk.END)
                Txtbx4.delete(0 , tk.END)
                confirm.withdraw()

            def taqr():
                pyautogui.doubleClick(1101 , 541)
                sleep(1)
                pyautogui.hotkey('ctrl' , 'a')
                sleep(0.5)
                pyautogui.keyDown('del')
                sleep(1)
                pyautogui.keyUp('del')
                sleep(0.5)
                pyautogui.write(str("jl hgjv;df ,hgjaydg ,hgavp ,hujlh] hgqlhk fjhvdo hghkjh[")) 
            """
            global confirm
            confirm = tk.Tk()
            confirm.title("تاكيد اذا كنت تريد المتابعه فى الحفظ ")
            confirm.geometry("230x100")
            lab1 = tk.Label(confirm , text="هل تريد المتابعه " , fg="red" , bg="yellow" , font=("Arial" , 20))
            lab1.pack()
            but = tk.Button(confirm , text="نعم" ,command=yes ,  fg="white" , bg="blue")
            but.pack()
            but.place(x=30 , y=40)
            but2 = tk.Button(confirm , text="لا" ,command=no , fg="white" , bg="red" )
            but2.pack()
            but2.place(x=100 , y=40)
            but3 = tk.Button(confirm , text="كتابة التقرير " , command=taqr ,fg="white" , bg="green")
            but3.pack()
            but3.place(x=160 , y=40)
            confirm.mainloop()
            """

        else:
            sleep(1)
            pyautogui.countdown(1)
            pyautogui.click(972 , 141)
            sleep(0.2)
            pyautogui.press('tab')
            sleep(0.5)
            pyautogui.press('tab')
            sleep(0.3)
            pyautogui.hotkey('alt' , 'down')
            sleep(0.2)
            pyautogui.press('up')
            sleep(0.2)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('up')
            sleep(0.1)
            pyautogui.press('enter')
            sleep(1)
            pyautogui.press('tab')
            sleep(0.2)
            pyautogui.press('tab')
            sleep(0.2)
            pyautogui.write(a)
            pyautogui.write(b)
            sleep(0.2)
            pyautogui.press('enter')
            sleep(0.2)
            pyautogui.write(c)
            sleep(0.2)
            pyautogui.press('enter')
            sleep(0.5)
            pyautogui.write(d)
            sleep(0.2)
            pyautogui.press('enter')
            sleep(1)
            pyautogui.click(849 , 314)
            sleep(1)
            pyautogui.click(1037 , 334)
            sleep(1)
            pyautogui.write(a)
            sleep(1)
            pyautogui.press('enter')
            pyautogui.doubleClick(654 , 542)
            sleep(2)
            pyautogui.click(1101 , 541)
            sleep(3)
            pyautogui.write(str("jl hgjv;df ,hgjaydg ,hgavp ,hujlh] hgqlhk"))
            sleep(1)
            pyautogui.press('enter')
            sleep(1)
            pyautogui.doubleClick(854 , 475)
            sleep(1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('down')
            sleep(0.1)
            pyautogui.press('enter')
            sleep(1)
            pyautogui.doubleClick(1090 , 240)
            sleep(1)
            pyautogui.press('enter')
            sleep(1)
            pyautogui.press('enter')
            sleep(1)
            def yes():
                sleep(0.1)
                pyautogui.hotkey('ctrl','s')
                sleep(0.1)
                pyautogui.press('enter')
                pyautogui.click(299 , 644)
                sleep(1)
                pyautogui.click(1068 , 373)
                sleep(0.1)
                for u in range(3):
                    pyautogui.press('down')
                    sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.press('down')
                sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.click(153 , 508)
                for b in range(3):
                    pyautogui.press('enter')
                    sleep(0.5)
                sleep(1)
                pyautogui.click(308 , 526)
                sleep(0.1)
                pyautogui.keyDown('down')
                sleep(2)
                pyautogui.keyUp('down')
                sleep(0.1)
                """
                for m in range(2):
                    pyautogui.press('enter')
                    sleep(1)
                """
                pyautogui.click(567 , 473)
                sleep(0.1)
                pyautogui.press('down')
                sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.click(851,136)
                sleep(0.1)
                pyautogui.press('down')
                sleep(0.1)
                pyautogui.press('enter')
                sleep(0.1)
                pyautogui.hotkey('ctrl','s')
                sleep(0.1)
                pyautogui.press('enter')
                Txtbx.delete(0 , tk.END)
                Txtbx2.delete(0 , tk.END)
                Txtbx3.delete(0 , tk.END)
                Txtbx4.delete(0 , tk.END)
                confirm.destroy()
            def no():
                Txtbx.delete(0 , tk.END)
                Txtbx2.delete(0 , tk.END)
                Txtbx3.delete(0 , tk.END)
                Txtbx4.delete(0 , tk.END) 
                confirm.destroy()
            def taqr():
                pyautogui.doubleClick(1101 , 541)
                sleep(1)
                pyautogui.hotkey('ctrl' , 'a')
                sleep(0.5)
                pyautogui.keyDown('del')
                sleep(1)
                pyautogui.keyUp('del')
                sleep(0.5)

                if a==b:
                    pyautogui.write("jl hgjv;df ,hgjaydg ,hgavp ,hujlh] hgqlhk fjhvdo hghkjh[") 
                else:
                    pyautogui.write("jl hgjv;df ,hgjaydg ,hgavp ,hujlh] hgqlhk")   
            confirm = tk.Tk()
            confirm.title("تاكيد اذا كنت تريد المتابعه فى الحفظ ")
            confirm.geometry("230x100")
            lab1 = tk.Label(confirm , text="هل تريد المتابعه " , fg="red" , bg="yellow" , font=("Arial" , 20))
            lab1.pack()
            but = tk.Button(confirm , text="نعم" ,command=yes ,  fg="white" , bg="blue")
            but.pack()
            but.place(x=30 , y=40)
            but2 = tk.Button(confirm , text="لا" ,command=no , fg="white" , bg="red" )
            but2.pack()
            but2.place(x=100 , y=40)
            but3 = tk.Button(confirm , text="كتابة التقرير " , command=taqr ,fg="green" , bg="yellow")
            but3.pack()
            but3.place(x=160 , y=40)
            confirm.mainloop()

        Wd2.destroy()    
        wd.deiconify()
    def sww2():
        wd.deiconify()
        Wd2.destroy()   
    wd.withdraw()
    Wd2 = tk.Tk()
    Wd2.config(bg="skyblue")
    Wd2.title("بلاغات داخل الضمان لم يتخطى 6 شهور")
    Wd2.geometry("400x350")
    llbl = tk.Label(Wd2 , text="pnc" ,fg='red' , bg="skyblue", font=("Arial" ,20))
    llbl.pack()
    Txtbx = tk.Entry(Wd2 , fg='red')
    Txtbx.pack()
    Txtbx.focus_set()
    llbl2 = tk.Label(Wd2 , text="serial number" ,fg='red',bg="skyblue" , font=("Arial" ,20))
    llbl2.pack()
    Txtbx2 = tk.Entry(Wd2 , fg='red')
    Txtbx2.pack()
    llbl3 = tk.Label(Wd2 , text="تاريخ الانتاج 1" ,fg='red' , bg="skyblue",font=("Arial" ,20))
    llbl3.pack()
    Txtbx3 = tk.Entry(Wd2 , fg='red')
    Txtbx3.pack()
    llbl4 = tk.Label(Wd2 , text="تاريخ التركيب" ,fg='red', bg="skyblue" , font=("Arial" ,20))
    llbl4.pack()
    Txtbx4 = tk.Entry(Wd2 , fg='red')
    Txtbx4.pack()
    btn_d = tk.Button(Wd2 , text="تقفيل" , command=dam1 ,width="50" , height="2", fg="blue" , bg="yellow")
    btn_d.pack(pady=10)
    btn_g =tk.Button(Wd2 , text="رجوع" , command=sww2 , width="50" , height="2", fg="white" , bg="green")
    btn_g.pack(pady=5)
    Wd2.deiconify()

def sign_in():
    global wd
    wd = tk.Tk()
    wd.bind('<Return>', esnadaa)
    wd.config(bg="skyblue")
    wd.title("Zanussi programming ")
    wd.geometry("230x1200")
    lb1 = tk.Label(wd , text="شركة زانوسى" , fg="red" , bg="skyblue", font=("tajawal" , 20))
    lb1.pack(pady="10")

    btnsho = tk.Button(wd , text="show", command=show , fg="green")
    btnsho.pack(pady=12)

    btn_o = tk.Button(wd , text="فتح الاوراكل" , command=strto , fg="blue" ,width="15" ,height="1", bg="yellow")
    btn_o.pack(pady=10)
    btn_c = tk.Button(wd , text="vpn غلق" , command=close_o , fg="blue" ,width="15" ,height="1", bg="yellow")
    btn_c.pack(pady=10)
    btn_c = tk.Button(wd , text="اسناد" , command=esnadaa , fg="blue" ,width="15" ,height="1", bg="yellow")
    btn_c.pack(pady=10)
    btn_d = tk.Button(wd , text="تسجيل" , command=sign , fg="blue" ,width="15" ,height="1", bg="yellow")
    btn_d.pack(pady=10)
    btn_e = tk.Button(wd , text="تقفيل بلاغات داخل الضمان  " , command=switch ,fg="blue" ,width="15" ,height="1", bg="yellow" )
    btn_e.pack(pady=10)
    btn_h = tk.Button(wd , text="الغير منفذ" ,width="15" ,height="1", command=un)
    btn_h.pack(pady=5)
    btn_v = tk.Button(wd , text="سحب التفارير" ,command=repor , bg='#6A6A6A' ,width="15" ,height="1", fg='red')
    btn_v.pack(pady=5)
    btn_j = tk.Button(wd , text="لم يتم الانتهاء من الاصلاح" ,command=warasha ,bg='#6A6A6A' , width="15" ,height="1",fg='red')
    btn_j.pack(pady=5)
    btn_z = tk.Button(wd , text="سحب تقارير البلاغات المفتوحة من الاوراكل" , command=oprepor , bg="blue" , fg="white" , height=1 , width=20)
    btn_z.pack(pady=5)
    btn_f = tk.Button(wd , text="غلق البرنامج" , command=close_app ,fg="white" ,width="15" ,height="1", bg="red" )
    btn_f.pack(pady=10)
    lbl50 = tk.Label(wd , text="   تم التطوير بواسطة حازم ايمن " , bg="skyblue")
    lbl50.pack(pady=10)
    global txt_time
    txt_time = tk.Entry(wd , width=30 )
    txt_time.pack(pady=5)
    txt_time.focus_set()
    wd.mainloop()



def login():
    password = ""
    passwrd = txt.get()
    if passwrd == password:
        wd_sign_in.destroy()
        sign_in()
        
    else:
        messagebox.showerror("Error" , "كلمة السر غلط الرجاء المحاولة فى مره اخرى وفى وقت لاحق")



global wd_sign_in

wd_sign_in = tk.Tk()

wd_sign_in.geometry("200x100+10+10")
txt = tk.Entry(wd_sign_in , show="*")
txt.place(x=50, y=20)
btn = tk.Button(wd_sign_in ,text ="تسجيل الدخول", command = login)
btn.place(x=50 , y=40)

wd_sign_in.mainloop()



